version functions added
They were there just commented out. They don't compile currently because
there is no release version:

error: ‘NOTFOUND’ was not declared in this scope
    6 | #define ODIN_DATA_VERSION_PATCH -128-NOTFOUND